# Generated by Django 3.2.3 on 2021-06-08 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0002_newuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='pythonquiz',
        ),
    ]
